### PR TITLE
Update hero.css and README.md

### PR DESCRIPTION
**Pull request by sb-decoder**
## Related Issue
- Issue No. #350 

## Changes you made :
- 1. Update README.md(made some changes to beautify it).
- 2. Add black color to description font .also changed font family and font weight.
- 3. Curved border of buttons in landing page.

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)

## Output Screenshots :

Screenshot 2022-10-31 123848

### CODE REVIEW

**Comment by sb-decoder** [comment]
Kindly check this and if you want any changes let me know. @Arun9739

**Comment by Arun9739** [comment]
@sb-decoder Good chanes !!  I appreciate that 👍 
But the black color is not properly visible in description. Plz change the color.
The readme is good, but add the website link : https://arun9739.github.io/Paryatana/

**Comment by sb-decoder** [comment]
> @sb-decoder Good chanes !! I appreciate that 👍 But the black color is not properly visible in description. Plz change the color. The readme is good, but add the website link : https://arun9739.github.io/Paryatana/

Ok I will change the color to white .
And the website link is Embedde in Paryatana Heading.

**Comment by sb-decoder** [comment]
@Arun9739 Check the changes plz

**Comment by Arun9739** [comment]
@sb-decoder Good !!
LGTM 🌟

**Pull request merged**
