### PR TITLE
added more favourite places in favourite.html

### PR DESCRIPTION
**Pull request by KAMYAVERMA**
## Addition of more places in favourite page
-Issue #145

## Changes you made :
- Added some more places in the page

## Check list :

- [x ] I have followed code style of this project.
- [x ] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x ] All the aspects mentioned in the issue are covered.
- [ x] The website is properly working after my changes.
- [x ] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

## Output Screenshots 👍🏼 

Screenshot 2022-10-08 192647

### CODE REVIEW

**Comment by Arun9739** [comment]
@KAMYAVERMA Good 👍 
But the last card "Tirthan valley" image is not properly aligned as seen in other cards.
Plz do the changes.

Add the updated screenshots after your changes.

**Comment by KAMYAVERMA** [comment]
Changed the image
Screenshot 2022-10-08 192647

**Comment by Arun9739** [comment]
Good to go @KAMYAVERMA 
LGTM 💯

**Comment by Arun9739** [comment]
@KAMYAVERMA why you have added the screenshot in the repository along with other files
Plz remove

**Comment by KAMYAVERMA** [comment]
oops! 
Removed👍

**Comment by Arun9739** [comment]
@KAMYAVERMA good
But as my policy I have added only Indian or subcontinent place names
Plz change the sahara desert to any any indian desert.
Thank you 👍

**Comment by KAMYAVERMA** [comment]
CHANGED.
<br>
tgar desrt

**Comment by Arun9739** [comment]
Good to go @KAMYAVERMA 
LGTM 🌟

**Pull request merged**
