### PR TITLE
Update Homenavbar.css

### PR DESCRIPTION
**Pull request by priyanshu070702**
## Related Issue
- Issue No. #196

## Changes you made :
- Updated navbar

## Describe the changes :

updated navbar with website icon and links

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

11 10 2022_22 11 48_REC

### CODE REVIEW

**Comment by priyanshu070702** [comment]
Will do it..

**Comment by priyanshu070702** [comment]
Done

**Comment by Arun9739** [comment]
@priyanshu070702 can you tell me which screenshot you have added there.
Is that related to our website.

**Comment by Arun9739** [comment]
@priyanshu070702 Due to no activity this issue will be closed.

**Pull request closed without merging**
