### PR TITLE
Added Commen Section for Interactivity

### PR DESCRIPTION
**Pull request by AryanSahoo-2003**
## Related Issue
- Issue No. #88

## Changes you made :
- About html
 -CSS

## Describe the changes :

Sir I have made a comment box using HTML and CSS only as when doing with php..I need to change the filename which I think would not be appropriate (from .html to .php) as .htaccess is not working on my local machine..

In my previous PR, I had a branch conflict so I made this by updating all and resolving it

It makes people who have went along with your services to interact with each other or raise a question regarding services.

## Check list :

- [x ] I have followed code style of this project.
- [ x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ x] All the aspects mentioned in the issue are covered.
- [ x] The website is properly working after my changes.
- [ x] 🌟 ed the repo

### Type of change :

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

before...
image

after...
image
Please check and confirm it under Hacktoberfest 2022

### CODE REVIEW

**Comment by AryanSahoo-2003** [comment]
Hello! Please confirm it under Hactoberfest -accepted 2022 label

**Comment by AryanSahoo-2003** [comment]
Sir please confirm it and check

**Comment by AryanSahoo-2003** [comment]
@Arun9739 Please confirm and merge my PR , I have contributed in improving your website!

**Comment by Arun9739** [comment]
Good to go @AryanSahoo-2003 
LGTM 🌟

**Comment by Arun9739** [comment]
@AryanSahoo-2003 Your changes have created lot of problems
From next time make sure to do the changes properly.
image

**Pull request merged**
