### PR TITLE
changed font style

### PR DESCRIPTION
**Pull request by WonderSTK**
## Related Issue
- Issue No. #101 

## Changes you made :
- changed font family to inter in page

## Describe the changes :

this change is required because inter font family is mostly used font family at present time google is also using this font family in there works

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
Screenshot (11)
Screenshot (12)

### CODE REVIEW

**Comment by WonderSTK** [comment]
all done

**Comment by Arun9739** [comment]
@WonderSTK Thank you for this PR
But you have to create new branch for each separate PR
You can't push commits into main branch.
Read the contributing guidelines

Plz make a new PR.

**Comment by WonderSTK** [comment]
I have created please see

**Comment by WonderSTK** [comment]
ok

**Pull request closed without merging**
