### PR TITLE
Changed the footer on all pages to stay constant.

### PR DESCRIPTION
**Pull request by RXBlade**

### CODE REVIEW

**Comment by RXBlade** [comment]
@Arun9739 Looks like #318 is already done. Fixed the buggy resolution on the logo as well

**Comment by RXBlade** [comment]
@Arun9739 will you check my PR?

**Comment by Arun9739** [comment]
@RXBlade Plz upload the screenshot of section where you have changed.

**Comment by RXBlade** [comment]
Here are some screenshots, it's the exact same footer on all pages, the consistency was so bad before.

Screenshot 2022-10-26 091027
Screenshot 2022-10-26 091053
Screenshot 2022-10-26 091106

**Comment by Arun9739** [comment]
@RXBlade Plz add issue number, description of changes, checklist(which was there in original PR format).
Follow the contributing guidelines.

**Comment by RXBlade** [comment]
Another one that only cares about useless templates... The issue was solved and I don't have the time or interest to write a documentation for this joke of a static, useless website.

Make someone else write your things.

**Comment by Arun9739** [comment]
@RXBlade It may be a joke website for joker people.
But it has got some reputation in hacktoberfest.
First learn to behave properly and give respect to small things also.
As mentioned in contributing guidelines you have not created a separate branch nor given description.

The documentation gives proper description of your work. It looks like you dont know to write the description. Plz learn it.
We force you to create issues, so as to make you work in proper direction. 

If you have contributed to this useless website means you have did for getting swags. Do the contribution for learning purpose.
Last thing, the template may look useless to useless people.

**Comment by Arun9739** [comment]
@RXBlade You actually didn't deserve anything other than insulting people. First learn to accept your mistake and work upon improving it.

**Pull request closed without merging**
