### PR TITLE
Added Trendy Card Design

### PR DESCRIPTION
**Pull request by aniketsinha2002**
I've added trendy card design with cool hover effect.

## Related Issue
- Issue No. #104 

## Changes you made :
- Added Trendy Card Design
- Modified Basic Cards Design To Trendy Cards Design (Glassmorphisim CSS)

## Describe the changes :

This card design will look more catchy and trendy than the previous one.
 

This change is required to give the website modern look.

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Output Screenshots :

image

### CODE REVIEW

**Comment by Arun9739** [comment]
@aniketsinha2002 It looks nice
But in the card the second symbol after the text 'travel' is not aligned with that text.
Make it aligned and put the screenshot of aligned symbol.
Thank you 😃

**Comment by aniketsinha2002** [comment]
I've updated the file according to the changes you mentioned above.

image

**Comment by Arun9739** [comment]
@aniketsinha2002 Good
plz resolve banch conflicts for merging

**Comment by aniketsinha2002** [comment]
@Arun9739 Sir, Resolved!

**Comment by Arun9739** [comment]
Good to go @aniketsinha2002 
LGTM 😃

**Pull request merged**
