### PR TITLE
Updated contact.html and added js/gmap.js

### PR DESCRIPTION
**Pull request by RathoreAbhiii**
## Related Issue
- Issue No. #46 

## Changes you made :
- Updated contact.html.
- Created js/gmap.js 

## Describe the changes :

- Placed the existing code for the google map into a new file 'gmap.js' as modifying it was causing the rest of the page to not  render properly that is, only the form section of the contact page was loading and the rest of the part above it was disappearing.   
- Added new code by creating a new script within the contact.html page using similiar methods as before (now gmap.js). 
- Included an API call in order to make the google map functional   

- I believe the problem was caused as there was no API call for the google map. However, it could have been something else as well.

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Output Screenshots :

![Screenshot_2022-10-05-16-53-54-10_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/91001195/194049502-8960f25f-033b-4f72-aa65-fb478498d0cb.jpg

### CODE REVIEW

**Comment by Arun9739** [comment]
@RathoreAbhiii Nice work
But plz put screenshot of the gmap 
Resolve branch conflicts

**Comment by RathoreAbhiii** [comment]
> @RathoreAbhiii Nice work But plz put screenshot of the gmap Resolve branch conflicts

Thank You! Yeah, will do that by today.

**Comment by RathoreAbhiii** [comment]
In the attached screenshot, you must able to see "for development purposes" watermarked over the google map. This is because I have generated an API key that belongs to my account. In order to be able to use it publicly, I will have to set up billing information in my Google Cloud account. You can set up your own API key with billing info. and replace it in the <script key="YOUR_API_KEY"> tag in the contact.html file. For more information, you can refer to : [Error Messages Maps | JavaScriptAPI](https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors). Again, had a really good experience working on this issue. Thanks!

**Comment by Arun9739** [comment]
Wow !!
You did really well !! 😃 
LGTM 💯

**Pull request merged**
