### PR TITLE
Fixes issue #293

### PR DESCRIPTION
**Pull request by Vedant-Manjrekar**
## Related Issue
- Issue No. #293

## Changes you made :
- Added Link to this Github repository in the footer

## Describe the changes :
- Link to redirect user to this Github repository was added along with a github logo in the "Follow us" section of footer which also redirects user to this repository.

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

Screenshot 2022-10-19 at 1 21 27 PM

### CODE REVIEW

**Comment by Arun9739** [comment]
@Vedant-Manjrekar Good
But plz mention the same in all page's footer.
You have changed it in only on home page.

Also resolve the branch conflicts.

**Comment by Arun9739** [comment]
@Vedant-Manjrekar Plz resolve branch conflicts for merging

**Comment by Vedant-Manjrekar** [comment]
Done @Arun9739 
Screenshot 2022-10-22 at 7 23 33 PM

**Comment by Arun9739** [comment]
@Vedant-Manjrekar There have been branch conflicts again
Plz resolve

**Comment by Vedant-Manjrekar** [comment]
See @Arun9739 there is no point in resolving the conflicts again and again if you are not going to my merged the PR in time. Last time I resolved the conflict was 6 days ago, that's reasonable amount of time to review and merge a PR

**Comment by Arun9739** [comment]
@Vedant-Manjrekar Sorry for the problem caused.
But as you have changed a lot of files, there is branch conflict arising after each merge.
I have not commented bcz I thought you would resolve it.

It would be better if you ca create a new PR, so for the better mergability. Else you can resolve also, no problem.

**Comment by Arun9739** [comment]
@Vedant-Manjrekar Due to inactivity this PR will be closed.

**Pull request closed without merging**
