### PR TITLE
Responsive Logo in Navbar and Footer.

### PR DESCRIPTION
**Pull request by AnirudhHanda**
## Related Issue
- Issue No. #215 

## Changes you made :
- Added Responsiveness to Logo at 991px in Navbar and at 630px in Footer.

## Describe the changes : 
- Initially the Navbar and Footer Logo was not Responsive for Screen sizes 991px and 630px, I made it to fit inside at these screen sizes and added responsiveness.

- This change makes the website look more professional and asthetic.

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

paryatana footer logo

https://user-images.githubusercontent.com/113718835/195426951-76116128-32b7-4ca0-80ca-aac813ada144.mp4

### CODE REVIEW

**Comment by Arun9739** [comment]
@AnirudhHanda Good
Plz resolve branch conflicts for merging

**Comment by AnirudhHanda** [comment]
> @AnirudhHanda Good Plz resolve branch conflicts for merging

Conflicts resolved, Kindly Merge into the main. Thank You...

**Comment by Arun9739** [comment]
@AnirudhHanda Good
LGTM 💯

**Comment by AnirudhHanda** [comment]
> @AnirudhHanda Good LGTM 💯

Thank you sir !

**Pull request merged**
