### PR TITLE
Added Shimla and Kashmir Img

### PR DESCRIPTION
**Pull request by aniket2003**
## Related Issue
- Issue No. #3

## Changes you made :
- Changed the Images for Shimla and Kashmir Section.

## Describe the changes :

Replaced the index-01.jpg and index-02.jpg images. 

The images at the Shimla and Kashmir section were irrelevant , thus the task was to replace them with new relevant images.

## Check list :

- [ x] I have followed code style of this project.
- [ x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ x] All the aspects mentioned in the issue are covered.
- [x ] The website is properly working after my changes.
- [x ] 🌟 ed the repo

### Type of change :

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Output Screenshots :

BEFORE : 

Screenshot (83)

AFTER:

Screenshot (82)

### CODE REVIEW

**Comment by aniket2003** [comment]
@Arun9739 Please close the issue if you find my solution relevant.

**Comment by Arun9739** [comment]
@aniket2003 thank you for your PR.
Please mention the correct issue number( I think your issue number is 3)
Please add a screenshot of web section where you changed.

**Comment by aniket2003** [comment]
@Arun9739 I have corrected the errors you can check it now , sorry for the inconvenience.

**Comment by Arun9739** [comment]
Good to go @aniket2003 
LGTM 🥳

**Pull request merged**
