### PR TITLE
Updated Footer Followup Design

### PR DESCRIPTION
**Pull request by pranjalT24**
## Related Issue
- Issue No. #242 

## Changes you made :
- Added Border Bottom to Footer Follow Us Text

## Describe the changes :

-The Follow Us text was looking little weird with underline text style so I decided to give border and padding giving will be the good option for that 

- It make the follow us text in footer looks little good

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Output Screenshots :

Screenshot 2022-10-13 at 10 49 23 PM

### CODE REVIEW

**Comment by Arun9739** [comment]
@pranjalT24 Plz add some screenshots and issue number, description and complete checklist.

**Comment by Arun9739** [comment]
@pranjalT24 plz resolve the branch conflicts for merging

**Comment by pranjalT24** [comment]
Conflict Resolved

**Comment by Arun9739** [comment]
@pranjalT24 LGTM 👍

**Pull request merged**
