### PR TITLE
Enhance contact page

### PR DESCRIPTION
**Pull request by zaahmed-nisum-com**
## Related Issue
- Issue No. [#323](https://github.com/Arun9739/Paryatana/issues/323)

## Changes you made :
Enhance contact page
- 

## Check list :

- [ yes] I have followed code style of this project.
- [ yes] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ yes] All the aspects mentioned in the issue are covered.
- [ yes] The website is properly working after my changes.
- [ yes] 🌟 ed the repo

### Type of change :

- [ no] Bug fix (non-breaking change which fixes an issue)
- [yes ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Arun9739** [comment]
@zaahmed-nisum-com Plz mention the issue number.

**Comment by zaahmed-nisum-com** [comment]
@Arun9739  done

**Comment by Arun9739** [comment]
@zaahmed-nisum-com Plz put the screenshot of section where you have changed

**Comment by zaahmed-nisum-com** [comment]
Screen Shot 2022-10-25 at 9 28 26 PM
Here it is

**Comment by zaahmed-nisum-com** [comment]
its a gif image you can check on codebase

**Comment by zaahmed-nisum-com** [comment]
@Arun9739  can you please review it and accept the MR

**Comment by Arun9739** [comment]
@zaahmed-nisum-com Good
LGTM 🌟

**Pull request merged**
