### PR TITLE
fixed the card responsiveness for tablet view in home page

### PR DESCRIPTION
**Pull request by swastik-bose007**
## Related Issue
- Issue No. #105

## Changes you made :
There was conflict between bootstrap default margin and custom margin so i removed bootstrap classes and make it simple using only custom CSS property.

## Describe the changes : 
I have observed the code structure and its rendering in webpage and I came to a conclusion that the additional margin used over bootstrap layout was causing the responsiveness issue so I have fixed the margin issue by removing row col bootstrap classes and made it simple with raw CSS property maintaining the margins. ##Apart from this i have added a box shadow in the cards which make better UI in this light tone website

This action solved the responsiveness issue in middle width devices (Tablets)

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Output Screenshots :

image

### CODE REVIEW

**Comment by Arun9739** [comment]
Good @swastik-bose007 
But plz resolve branch conflicts for merging

**Comment by swastik-bose007** [comment]
It's resolved please check it now

**Comment by Arun9739** [comment]
@swastik-bose007 Sorry for inconvenience
But again there have been conflicts. Plz resolve.

**Comment by swastik-bose007** [comment]
Give me just 10 minutes I am working immediately

**Comment by swastik-bose007** [comment]
Done

**Comment by Arun9739** [comment]
Good to Go @swastik-bose007 
LGTM 👍

**Comment by Arun9739** [comment]
@swastik-bose007 Your changes created some problems
Bcz you haven't properly handled latest commits made by other people.
Next time create proper changes.
You can work on this again if you wish.

**Pull request merged**
