### PR TITLE
Fixed fav icon error in title bar

### PR DESCRIPTION
**Pull request by divyansh956**
## Related Issue
- Issue No. #235 

## Changes you made :
- Fixed the fav icon bug of the title bar

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### Previous:
image
image
image
image

### After: 
image
image
image
image

### CODE REVIEW

**Comment by Arun9739** [comment]
@divyansh956 Plz mention the issue number

**Comment by divyansh956** [comment]
> @divyansh956 Plz mention the issue number

Updated

**Comment by Arun9739** [comment]
@divyansh956 can you update the same to all pages
You have made it only to home page.
Plz do for other pages such as about, favurites, tours ....

**Comment by divyansh956** [comment]
> @divyansh956 can you update the same to all pages You have made it only to home page. Plz do for other pages such as about, favurites, tours ....

Updated for all pages

**Comment by Arun9739** [comment]
@divyansh956 Good to go
LGTM 🌟

**Pull request merged**
