### PR TITLE
fix issue #340 Logo placement is wrong

### PR DESCRIPTION
**Pull request by hokandil**
## Related Issue
- Issue No. #340 

## Changes you made :
- removed inline style of the logo image from all html files and used an id to link to CSS logo file

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :
image

### CODE REVIEW

**Comment by Arun9739** [comment]
@hokandil Nice !!
Plz chnage the same in all pages
The same problem is present in other pages also.

**Comment by hokandil** [comment]
@Arun9739 All Done

**Review by hokandil — COMMENTED** [review]
@Arun9739  All Done

**Comment by Arun9739** [comment]
@hokandil Good
LGTM 🌟

**Pull request merged**
