### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Z3RO-O**
## Related Issue
- Issue No. #44 

## Changes you made :
- Button styling
- Theme of Website
- Effects on hover
- Making the content more readable using good color combos

Better Look
Screenshot (24)
Screenshot (25)
Screenshot (26)

### CODE REVIEW

**Comment by Arun9739** [comment]
Good to go @Z3RO-O 
Nice UI 👍 
LGTM 💯

**Comment by Arun9739** [comment]
@Z3RO-O Your PR created some problems
Like it most buttons were not displayed properly.
Hence this PR will be invalid.
Next time plz create properly.

You can try it once again, if you wish.

**Comment by Z3RO-O** [comment]
Sorry but the problems were not due to my code.

**Comment by Z3RO-O** [comment]
please remove the tag of invalid pr

**Pull request merged**
