### PR TITLE
FOOTER GENERALIZATION

### PR DESCRIPTION
**Pull request by Devrajsinh03**
## Issue
Issue no. #325

## Changes you made :
- Generalised Footer on all the pages.

## Describe the changes :

the change was required because the footer was enhanced in the index.html and was not enhanced in other pages breaking the consistency of the website. 

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

Image not required as the footer is same as that is rendered in  index.html

### CODE REVIEW

**Comment by Arun9739** [comment]
@Devrajsinh03 Plz mention the issue number.

**Comment by Devrajsinh03** [comment]
@Arun9739 created and added issue number

**Comment by Arun9739** [comment]
@Devrajsinh03 I have mentioned the reason for closing the PR in #325

**Comment by Arun9739** [comment]
@Devrajsinh03 This issue is not yet solved but has been assigned to someone else.
Plz look at the currently open issues, you will see there.

**Comment by Devrajsinh03** [comment]
@Arun9739 okay 👍

**Pull request closed without merging**
