### PR TITLE
added smooth animation and responsiveness

### PR DESCRIPTION
**Pull request by Naushad-dev**
## Related Issue
- Issue No. #97 

## Changes you made :
- I have made the hover effect more smooth by adding transition to it in About page on WHO WE ARE SECTION .
- Also added space and margins between two cards in Mobile View which make the animation more perfect and smooth. 

## Describe the changes :

-I have added more gaps between the two cards in Mobile View so that the animation looks more perfect 

## Checklist :

- [x] I have followed the code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Before

https://user-images.githubusercontent.com/106610708/194381597-c7ca17d8-fff9-4f90-b787-b22dbdd00216.mp4

###After

https://user-images.githubusercontent.com/106610708/194382114-e4fd34bf-24b4-4532-9bdf-c951ebf0f39f.mp4

### CODE REVIEW

**Comment by Naushad-dev** [comment]
This is my first Open Source Contribution😅 so if something went wrong please guide me thank you!

**Comment by Arun9739** [comment]
@Naushad-dev good 👍 
But resolve branch conflicts

**Comment by Naushad-dev** [comment]
Resolved the conflict, Sir 👍

**Comment by Arun9739** [comment]
Good to go @Naushad-dev 
LGTM 🤩

**Pull request merged**
