### PR TITLE
Update footer.css

### PR DESCRIPTION
**Pull request by Devrajsinh03**
## Related Issue
- Issue No. #229

## Changes you made :
- changed hover color to #FCDD44

## Describe the changes :

better UI

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

- before
Screenshot 2022-10-13 at 10 05 36 AM

- after
Screenshot 2022-10-13 at 10 05 45 AM

### CODE REVIEW

**Comment by Arun9739** [comment]
@Devrajsinh03 Good
But along with color can you add some transition of 1.3?
Bcz the present footer has some transition, you can see in live website.
But the footer's screenshot which you have added doesn't showing any transition effect.

**Comment by Devrajsinh03** [comment]
@Arun9739 I have made hover bit better for issue #229 if you can merge it.

**Comment by Devrajsinh03** [comment]
@Arun9739 I've added transition too

**Comment by Arun9739** [comment]
@Devrajsinh03 Good 
LGTM 👍

**Pull request merged**
